# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Arty-A7-35-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_2/design_1_clk_wiz_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_2 || ORIG_REF_NAME==design_1_clk_wiz_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reset_inv_0_0/design_1_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reset_inv_0_0 || ORIG_REF_NAME==design_1_reset_inv_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_2 || ORIG_REF_NAME==design_1_microblaze_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_3/design_1_dlmb_v10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_3 || ORIG_REF_NAME==design_1_dlmb_v10_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_3/design_1_ilmb_v10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_3 || ORIG_REF_NAME==design_1_ilmb_v10_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_3/design_1_dlmb_bram_if_cntlr_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_3 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_3/design_1_ilmb_bram_if_cntlr_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_3 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lmb_bram_3/design_1_lmb_bram_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_3 || ORIG_REF_NAME==design_1_lmb_bram_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_1_3/design_1_mdm_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mdm_1_3 || ORIG_REF_NAME==design_1_mdm_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_0_100M_3/design_1_rst_clk_wiz_0_100M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_100M_3 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_100M_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_4 || ORIG_REF_NAME==design_1_axi_gpio_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_2/design_1_axi_uartlite_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_2 || ORIG_REF_NAME==design_1_axi_uartlite_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_3/design_1_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_3 || ORIG_REF_NAME==design_1_xbar_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_3/design_1_microblaze_0_axi_periph_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_3 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_3} -quiet] -quiet

# XDC: c:/Users/rikir/Documents/FPGA_projects/project_getting_started_Vivado_Vitis/project_getting_started_Vivado_Vitis.gen/sources_1/bd/design_1/design_1_ooc.xdc
